### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Sakulq** [safex/safexcore#1]
[ 73%] Linking CXX executable core_tests
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "cryptonote::get_base_reward(unsigned long long)", referenced from:
      gen_block_reward::check_block_rewards(cryptonote::core&, unsigned long, std::__1::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings>, std::__1::allocator<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> > > const&) in block_reward.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [tests/core_tests/core_tests] Error 1
make[2]: *** [tests/core_tests/CMakeFiles/core_tests.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [release-all] Error 2

i'm using iOSx

**Comment by atanmarko** [comment]
Thanks @Sakulq for the report.
Any more details about build environment?

**Comment by Sakulq** [comment]
macOS High Sierra 10.13

**Comment by atanmarko** [comment]
Issues reproduced also on Ubuntu 16.04. 
Please try fix #4

**Comment by Sakulq** [comment]
i created an ubuntu partition, everything worked fine !
