### ISSUE TITLE
Algorithm?

### ISSUE THREAD

**Issue by freebet** [safex/safexcore#13]
Hi,

Someone can tel me Safexcore wich algo? Cryptonight v7, cryptonight fast, cryptonight original or heavy?

i cant mine on the pool (https://safexpool.net/). 

xmrstak error:

`SOCKET ERROR - [safexpool.net:3333] CALL error: Timeout while waiting for a reply`

and I've tried on nodejs-pool, same problem: "SOCKET ERROR".

Thanks.

**Comment by atanmarko** [comment]
We have forked from Monero around middle of April (so between Monero releases  v0.12.0.0 and v0.12.1.0). So far we have not changed mining algorithm after fork, so it is Moneros Cryptonight v7

**Comment by ddabek** [comment]
mining pool integration will take place in near future (2 weeks or so from now; so please standby this pool was not yet configured by our team)
