### ISSUE TITLE
PreRelease contains Hardfork definition that happened in the past

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [safex/safexcore#194]
Hi!

By using latest stable release (3.0.1) I can't get past block 335252 which was mined on 20191211.
When Safex 5.0.0 will be latest stable release it will bring compatibility with events that happened in the past. Right now, stable release is not working anymore.

Tldr:
You've commited the code with breaking changes two hours before they happened.
You've wrongly released code as PreRelease instead of stable release.
Are you serious?

**Comment by VanGrx** [comment]
Hello.

Regarding Your comments:

>  You've commited the code with breaking changes two hours before they happened.

The changes in 3.0.1 were a precaution for a possible forking during the transition period of 60 blocks. The 3.0.0 nodes could be used all up until 5.0.0 is released so no damage was done. There was a very high possibility that the issue would never happen during that transition as it would need multiple nodes to mine alternative blocks with the difficulty set high enough, but we wanted to be 100% sure that the hard-fork passes smoothly and not postpone, which turned to be a good decision.

>  You've wrongly released code as PreRelease instead of stable release.

You are correct, the 5.0.0 is actually a stable release. I am sorry for this mistake. It is changed now.

>  Are you serious?

I did my best, it wasn’t much
I couldn’t feel, so I tried to touch
I’ve told the truth, I didn’t come to fool you
And even though it all went wrong
I’ll stand before the lord of song
With nothing on my tongue but hallelujah

Hope this answers helped
