### ISSUE TITLE
error while loading shared libraries: libnorm.so

### ISSUE THREAD

**Issue by nullart2** [safex/safexcore#255]
running  safexd-linux-7.0.1 shows this error

OS: Debian 9

```
error while loading shared libraries: libnorm.so.1: cannot open shared object file: No such file or directory
```

**Comment by ddabek** [comment]
Hey @nullart2 please make sure that you have installed all of the required dependencies:
https://github.com/safex/safexcore#ubuntu-1804

For libnorm.so.1 specifically: `sudo apt install libnorm-dev` 
should do the trick!

Thank you for raising your issue :)
