### ISSUE TITLE
Can't make on Mac OS

### ISSUE THREAD

**Issue by SenhorCastor** [safex/safexcore#3]
Hi, not a C developer so I might be missing something obvious
```
Determining if the function rl_copy_text exists failed with the following output:
Change Dir: /Users/fernandomartin/projects/safexcore/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_fdf64/fast"
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_fdf64.dir/build.make CMakeFiles/cmTC_fdf64.dir/build
Building C object CMakeFiles/cmTC_fdf64.dir/CheckFunctionExists.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -fno-strict-aliasing -maes -std=c11 -D_GNU_SOURCE   -Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Waggregate-return -Wnested-externs -Wold-style-definition -Wstrict-prototypes -march=native  -fPIC  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fno-strict-aliasing -DCHECK_FUNCTION_EXISTS=rl_copy_text -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk   -o CMakeFiles/cmTC_fdf64.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.11.4/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_fdf64
/usr/local/Cellar/cmake/3.11.4/bin/cmake -E cmake_link_script CMakeFiles/cmTC_fdf64.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -fno-strict-aliasing -maes -std=c11 -D_GNU_SOURCE   -Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Waggregate-return -Wnested-externs -Wold-style-definition -Wstrict-prototypes -march=native  -fPIC  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fno-strict-aliasing -DCHECK_FUNCTION_EXISTS=rl_copy_text -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_fdf64.dir/CheckFunctionExists.c.o  -o cmTC_fdf64 /usr/lib/libreadline.dylib 
Undefined symbols for architecture x86_64:
  "_rl_copy_text", referenced from:
      _main in CheckFunctionExists.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_fdf64] Error 1
make: *** [cmTC_fdf64/fast] Error 2


ip-172-17-0-46:safexcore fernandomartin$ which xco
ip-172-17-0-46:safexcore fernandomartin$ XCo
ip-172-17-0-46:safexcore fernandomartin$ xcode
xcode-select  xcodebuild    xcodeproj     
ip-172-17-0-46:safexcore fernandomartin$ /usr/bin/xcodebuild -version
Xcode 9.2
Build version 9C40b
ip-172-17-0-46:safexcore fernandomartin$ 
```
Xcode version 9.2.
OS MacOs Sierra 10.13.4

I ran into several issues, finally got stuck in:
```
ld: symbol(s) not found for architecture x86_64
```
Googled around stackoverflow. Found this:

```
Hi, I know... it's an old post but here it comes my answer.
I use OS X Sierra and g++ command to compile cpp in the terminal and I got that error too.
How I solved that? I used -lm or -ll or -ly as parameters of g++ command. For me -lm worked but for some friends doesn't so maybe you have to try with the others. Try to combine them too.
```
on https://github.com/ucbrise/clipper/issues/300

But I havent programmed in C or used g++ so I dont know what -lm means.

Hope it helps

**Comment by atanmarko** [comment]
From your console error printout seems like your build is using clang C++ compiler? 

Referent environment we have mostly used during development is Ubuntu 16.04/18.04 and g++. Please try build with g++.

**Comment by dhniels** [comment]
@SenhorCastor if you figure out how to compile and use the safex blockchain on MacOS, post a little writeup on your blog or something (if you have one) I'm new to this but would like to try it and the new testnet and mining on my MacBook just for fun :)

**Comment by Kiu0612** [comment]
I have managed to build it on Mac High Sierra 10.13, I'll post instructions a bit later

**Comment by SenhorCastor** [comment]
Thanks @Kiu0612 !!!

**Comment by Kiu0612** [comment]
-Check if you have Developer Tools Installed
`$ xcode-select -p`
-If you don't have Developer Tools, install it. If you do, skip this step
`$ xcode-select --install`
-Clone the git repository with recursive
`$ git clone https://github.com/safex/safexcore.git --recursive`
-Go into safexcore folder
`$ cd safexcore`
-Check if brew is installed
`$ which brew`
-If you don't have brew installed, install it. If you have it, skip this step
`$brew install wget`
-Install all libraries
```
$ brew tap jmuncaster/homebrew-header-only
$ brew install cmake boost zmq czmq zeromq jmuncaster/header-only/cppzmq openssl pkg-config
$ brew install libzmq
```
-You will need to have MacPorts installed. If you don't have it install it from here https://guide.macports.org/. Download the package for your OS version from the website. Open new terminal window and check if MacPorts are installed
`$ port version`
Then install readline using MacPorts
`$ sudo port install readline`
-Build it and insert the number of cores you have
`$ make -j<Your number of cores> debug-all`

**Comment by SenhorCastor** [comment]
Thanks! I will take a look tonight. I believe that I might have not done --recursive

**Comment by freebet** [comment]
for ubuntu without problem:

`git clone --recursive https://github.com/safex/safexcore.git`
`cd safexcore && git submodule init && git submodule update`
`cmake .`
`make`

**Comment by SenhorCastor** [comment]
freebet code works. I was missing the recursive flag on git clone.

Going to close

**Comment by SenhorCastor** [comment]
thanks @freebet and rest!

**Comment by dhniels** [comment]
@Kiu0612 thanks for the writeup, however brew doesn't find the libzmq package and their repo says to install zeromq instead. wonder if this breaks the setup?
