### ISSUE TITLE
safex-wallet-rpc not created

### ISSUE THREAD

**Issue by cool-pool** [safex/safexcore#45]
After change in CMakeList.txt file option for RPC Wallet to ON not builded

---------------
#when ON - it will build safex-wallet-rpc
option(BUILD_WALLET_RPC "Build cli rpc wallet server." ON)

-----------------------

**Comment by cool-pool** [comment]
fixed by git from master and not from develop

**Comment by PsychoSterope** [comment]
@cool-pool How did you fix this problem exactly?
