### ISSUE TITLE
safex-wallet-rpc not created

### ISSUE THREAD

**Issue by PsychoSterope** [safex/safexcore#49]
Tried to ask in discord and got ignored. Nice one!

So even when you enable create wallet rpc in the cmakelists.txt it doesn't make the rpc wallet. What is the solution to this?

**Comment by ddabek** [comment]
Let's answer your question; 

We have a task to check this out tomorrow; however it usually will build if you run make again for a second time. And on the second run it compiles the rpc wallet build.

**Comment by PsychoSterope** [comment]
That worked! Thanks @ddabek
