### ISSUE TITLE
Compilation issue on Fedora 28

### ISSUE THREAD

**Issue by denifednu** [safex/safexcore#5]
On Fedora 28, fails to compile many files due to error:
`use copy-assignment or copy-initialization instead [-Werror=class-memaccess]`
One example:
`safexcore/src/crypto/chacha.h:77:46: error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of non-trivially copyable type ‘using chacha_key = tools::scrubbed_arr<unsigned char, 32>’ {aka ‘struct tools::scrubbed<std::array<unsigned char, 32> >’}; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]`
As a kludgy workaround I commented out the following line in:
`src/CMakeLists.txt` and `contrib/CMakeLists.txt`: `add_compile_options("${WARNINGS_AS_ERRORS_FLAG}")`
Then it built successfully.

**Comment by denifednu** [comment]
Yes, would be willing to investigate more.  Please advise how I could help.

The `WARNINGS_AS_ERRORS_FLAG` is turning on `-Werror=class-memaccess` which causes the warning to turn into an error.  I did a little research and found many projects (including monero) hitting this issue with gcc 8.1 compiler and they updated their code so it no longer fails, examples:
https://github.com/monero-project/monero/issues/3797
https://github.com/ColinDuquesnoy/MellowPlayer/issues/193

As a workround Linux/GCC could be added to the if statement in CMakeLists.txt:
```
# warnings are cleared only for GCC on Linux`
if (NOT (MINGW OR APPLE OR FREEBSD OR OPENBSD OR DRAGONFLY))`
   add_compile_options("${WARNINGS_AS_ERRORS_FLAG}") # applies only to targets that follow`
endif()`
```

Here is requested info:

```
$ g++ --version
g++ (GCC) 8.1.1 20180502 (Red Hat 8.1.1-1)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ldd --version
ldd (GNU libc) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by atanmarko** [comment]
Well, any kind of help is more than welcomed :)

You could try to figure out the real reason behind this compiler error, what in the source code of _safexcore/src/crypto/chacha.h_ itself is triggering this compiler warning (and hence error). That would be the better way to solve it. 

Worse way would be to disable warning as error for this particular warning _-Wno-error=class-memaccess_, but also to isolate this workaround as much as possible, i.e. only for GCC version >8, Linux OS and only in safexcore/src/crypto/CMakeLists.txt. CMake gives much flexibility and power for this kind of configurations. We do not want to globally disable warnings as errors as they remind us and force us to pay more attention to code quality. 

If you have some good proposal for solution feel free to make fork and pull request ;)

**Comment by hitripekac** [comment]
@denifednu can you try to build with changed in pr #8? We merged some changes that fix the build issues with

**Comment by denifednu** [comment]
@hitripekac built with latest code, issue is resolved, thank you!

Safex 'Safex Blockchain Launch v0.1' (v0.1-master-b541aae)
