### ISSUE TITLE
Dvandal's  cryptonote-nodejs-pool 

### ISSUE THREAD

**Issue by PsychoSterope** [safex/safexcore#50]
Trying to setup this pool and I keep getting:
Malformed message from ::ffff:174.74.89.112 generated an exception. Message: {"id":1,"jsonrpc":"2.0","method":"login","params":{"login":"Safex5zFa7NVATj8EWHdoDEiF1WiDYFBGMRE9whi9AhMG5T4teT6ht9TCkcSQKW48pgn4divLexfMXe5qFFXRWh6X3m7aQtCGfF2k","pass":"x","agent":"XMRig/2.7.3-beta (Windows NT 10.0; Win64; x64) libuv/1.22.0 msvc/2017","algo":["cn/1","cn/0","cn/xtl","cn/msr","cn/xao","cn/rto","cn"]}}
[pool] (Thread 2) Exception: Failed to parse block

I am assuming the "intAddressPrefix" is wrong, anyone have any ideas what the problem could be?

**Comment by ddabek** [comment]
Thanks @PsychoSterope we are in progress with getting public sharing mining pools going; please submit any other issues you've encountered. The one you mentioned is common; we're on it :muscle:

**Comment by PsychoSterope** [comment]
@ddabek I have everything ready to go except that issue. I just don't know how to solve it.

**Comment by PsychoSterope** [comment]
So safex.xmining.pro has it up and running, so there has to be a fix. No one seems to want to share the fix or no one else knows. What gives? @ddabek 

Sorry if I sound grumpy, I am just frustrated.

**Comment by atanmarko** [comment]
Hi @PsychoSterope!
We are working to setup cryptonote-xmr-pool, but we are not there yet. It is using https://github.com/kirichenko/node-cryptonote-util.git#xmr-Nan-2.0 which has quite outdated cryptonote C++ code (hence the "Failed to parse block" error).

We will publish pool source code as soon as we make it functional.

**Comment by PsychoSterope** [comment]
@atanmarko Ok cool. Thing is though cryptonote-nodejs-pool is maintained and uses the newest https://github.com/MoneroOcean/node-cryptonight-hashing and https://github.com/MoneroOcean/node-cryptoforknote-util. Wouldn't it be easier to use what's already known? It seems one pool already is, but refuses to share with the community.

I am not smart enough to fix it, but someone besides the one person must be able to, I just wish it was me.

**Comment by atanmarko** [comment]
@PsychoSterope Still work in progress, and not tested enough, but seems to be functional (on the test network and develop branch) - check https://github.com/atanmarko/cryptonote-safex-pool

**Comment by PsychoSterope** [comment]
Solution has been found and pool is up, running, finding blocks, and making payouts!
