### ISSUE TITLE
compiling error running Make File in Ubuntu 

### ISSUE THREAD

**Issue by friedner** [safex/safexcore#64]
I receive the following error at 64%:  I am using Ubuntu 18.4, I have 8GB RAM 

[ 62%] Building CXX object src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_tx_utils.cpp.o
In function ‘bool cryptonote::construct_miner_tx(size_t, size_t, uint64_t, size_t, uint64_t, const cryptonote::account_public_address&, cryptonote::transaction&, const blobdata&, size_t, uint8_t)’:
cc1plus: error: ‘void* __builtin_memset(void*, int, long unsigned int)’: specified size 18446744073709551608 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
cc1plus: all warnings being treated as errors
src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/build.make:134: recipe for target 'src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_tx_utils.cpp.o' failed
make[2]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_tx_utils.cpp.o] Error 1
CMakeFiles/Makefile2:1312: recipe for target 'src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/all' failed
make[1]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
tommy@tommy-VirtualBox:~/safexcore$

**Comment by atanmarko** [comment]
It seems to me that build process was struck with limited resources from system.  What is an allocated memory/number of CPU cores for virtual box image? Try to increase them, and to build will fewer threads (e.g -j2 or even -j1). Try also to build from scratch (delete build folder before rebuilding).

**Comment by friedner** [comment]
Will try that
-thank you

**Comment by friedner** [comment]
I added more RAM, now have 16GB and did Make -J1.  Still  got hung up on the same line:

[ 62%] Building CXX object src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_tx_utils.cpp.o
In function ‘bool cryptonote::construct_miner_tx(size_t, size_t, uint64_t, size_t, uint64_t, const cryptonote::account_public_address&, cryptonote::transaction&, const blobdata&, size_t, uint8_t)’:
cc1plus: error: ‘void* __builtin_memset(void*, int, long unsigned int)’: specified size 18446744073709551608 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
cc1plus: all warnings being treated as errors
src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/build.make:134: recipe for target 'src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_tx_utils.cpp.o' failed
make[2]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_tx_utils.cpp.o] Error 1
CMakeFiles/Makefile2:1312: recipe for target 'src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/all' failed
make[1]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by atanmarko** [comment]
Are you sure that you have installed all [dependencies](https://github.com/safex/safexcore/blob/master/README.md#ubuntu-1804) in Virtual Box?
If yes, could you please provide detailed steps from vanilla Virtual Box installation how you get to this error?

**Comment by hitripekac** [comment]
Found the issue. It's a problem with the new versions of GCC (see [83239](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83239)). The issue should be fixed in master branch now. Please pull and try building again.
