### ISSUE TITLE
Release .zip and .tar.gz doesn't cointain recursive submodules

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [safex/safexcore#81]
When downloaded safexcore zip from release pages, subdirectories of git submodules are empty.
Ready-to-go release packages should contain such files.

**Comment by atanmarko** [comment]
Thanks for pointing out!
Github makes automatically source code files from the particular commit that does not include submodules. We'll check how to deal with that.

**Comment by atanmarko** [comment]
Seems that it is not possible to do it automatically.

https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release

You can always download source code from release branch:
`git clone https://github.com/safex/safexcore.git --branch release-v0.1.1 --recursive`

**Comment by KrzysztofHajdamowicz** [comment]
Is it a proper fix? I doubt so.
Proper fix should be done by taking down broken downloads and fixing manual about getting the code.

**Comment by atanmarko** [comment]
Thanks for suggestions. You are welcome to help us and propose a way how to patch Github source code release procedure, as it does not give option to change or remove zip and tar.gz file included in the release. Binaries are created and uploaded manually, but source code files are directly tied to the commit/tag on the branch, and Github packs them and attaches them to the release in the background without exposing customization option.
Instructions how to clone and compile from source code are available in Readme.
In case you have any ideas how we can improve things, please create a pull request and we will be happy to review and integrate it.
