### ISSUE TITLE
libzmq.so.5 => not found

### ISSUE THREAD

**Issue by theDavidCoen** [safex/safexcore#84]
I'm installing safexd-ubuntu 16 but when I run ./safexd-ubuntu I have error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory

With ldd ./safexd-ubuntu16 I have libzmq.so.5 => not found
Could you help me?

**Comment by atanmarko** [comment]
Are you using Ubuntu 16.04? _safexd-ubuntu16_ links _libzmq_ dynamically, so just install it with `sudo apt-get install libzmq5`. For Ubuntu 16.04 list of shared libraries that need to be present on the system is given [here](https://github.com/safex/safexcore/releases/tag/v0.1.1-Ubuntu16).

 If you are on 18.04, please use this [release](https://github.com/safex/safexcore/releases/tag/v0.1.1), _safexd-linux_ binary.

**Comment by theDavidCoen** [comment]
with sudo apt-get install libzmq5 it gives me
E: Unable to locate package libzmq5
I just find out I have ubuntu 14.04.5

**Comment by atanmarko** [comment]
Ubuntu 14.04 is quite outdated system and is unfortunately not supported from our side.
