### ISSUE TITLE
Missing 0.1.2 OSX binaries 

### ISSUE THREAD

**Issue by cpascoli** [safex/safexcore#97]
Under safexcore/releases/tag/v0.1.2 there are Ubuntu and Windows binaries but OSX binaries are missing. Please add Mac binaries for latest CLI tags.

**Comment by atanmarko** [comment]
Done, sorry for not updating issue imidiatelly

**Comment by cpascoli** [comment]
no worries. it's worth mentioning in the release nodes that on macOS the user needs to install
